FILE(TO_CMAKE_PATH "$ENV{SISODIR5}" SISODIR5)
FILE(TO_CMAKE_PATH "$ENV{SISODIR4}" SISODIR4)
FILE(TO_CMAKE_PATH "$ENV{SISODIRME4}" SISODIRME4)
FILE(TO_CMAKE_PATH "$ENV{SISODIR}" SISODIR)

IF (SISODISPLAYLIB_INCLUDE_DIR AND SISODISPLAYLIB_LIBRARY)
	SET(SISODISPLAYLIB_FIND_QUIETLY TRUE)
ENDIF (SISODISPLAYLIB_INCLUDE_DIR AND SISODISPLAYLIB_LIBRARY)

FIND_PATH(SISODISPLAYLIB_INCLUDE_DIR NAMES SisoDisplay.h fgrab_prototyp.h
	PATHS
	${CMAKE_INSTALL_PREFIX}/include
	${SISODIR5}/include
	${SISODIR}/include
	${SISODIR4}/include
	${SISODIRME4}/include
	"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Silicon Software GmbH\\Runtime5;Info]/include"
)

INCLUDE(SisoLibDir)
SISO_LIB_DIR("${SISODIR5}/lib" LIB_DIRS COMPILER_LIB_DIR)
SISO_LIB_DIR("${SISODIR4}/lib" LIB_DIRS)
SISO_LIB_DIR("${SISODIRME4}/lib" LIB_DIRS)
SISO_LIB_DIR("${SISODIR}/lib" LIB_DIRS)

FIND_LIBRARY(SISODISPLAYLIB_LIBRARY NAMES display display_lib
	PATHS
	${CMAKE_INSTALL_PREFIX}/lib/${COMPILER_LIB_DIR}
	${CMAKE_INSTALL_PREFIX}/lib
	${LIB_DIRS}
	"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Silicon Software GmbH\\Runtime5;Info]/lib/${COMPILER_LIB_DIR}"
	"[HKEY_LOCAL_MACHINE\\SOFTWARE\\Silicon Software GmbH\\Runtime5;Info]/lib"
)

IF (SISODISPLAYLIB_LIBRARY AND SISODISPLAYLIB_INCLUDE_DIR)
	SET(SISODISPLAYLIB_FOUND TRUE)
ENDIF (SISODISPLAYLIB_LIBRARY AND SISODISPLAYLIB_INCLUDE_DIR)

IF(SISODISPLAYLIB_FOUND)
	IF(NOT SISODISPLAYLIB_FIND_QUIETLY)
		MESSAGE(STATUS "Found SiSo display library: ${SISODISPLAYLIB_LIBRARY}")
	ENDIF(NOT SISODISPLAYLIB_FIND_QUIETLY)
	SET(SISODISPLAYLIB_LIBRARIES ${SISODISPLAYLIB_LIBRARY})
ELSE(SISODISPLAYLIB_FOUND)
	IF(SISODISPLAYLIB_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "SiSo display library not found")
	ENDIF(SISODISPLAYLIB_FIND_REQUIRED)
ENDIF(SISODISPLAYLIB_FOUND)
