INCLUDE(CheckIncludeFile)
INCLUDE(CheckFunctionExists)

CHECK_INCLUDE_FILE(stdint.h HAVE_STDINT_H)

IF (NOT SISOPLATFORM_DIR)
	FIND_PATH(SISOPLATFORM_MODULE_PATH "SisoPlatform.cmake" ${CMAKE_MODULE_PATH})
	SET(SISOPLATFORM_DIR "${SISOPLATFORM_MODULE_PATH}/../../include"
			CACHE PATH "Path to SisoPlatform include files")

	IF (UNIX AND NOT WIN32)
		ADD_DEFINITIONS(-DMEUNIX)
	ENDIF (UNIX AND NOT WIN32)
ENDIF (NOT SISOPLATFORM_DIR)

INCLUDE_DIRECTORIES("${SISOPLATFORM_DIR}")

IF (NOT HAVE_STDINT_H)
	IF (MSVC)
		FIND_PATH(SISOPLATFORM_FILE_PATH "SisoPlatform.cmake" ${CMAKE_MODULE_PATH})
		GET_FILENAME_COMPONENT(SISOPLATFORM_MODULE_PATH "${SISOPLATFORM_FILE_PATH}" PATH)
		INCLUDE_DIRECTORIES("${SISOPLATFORM_DIR}/msinttypes")
	ELSE (MSVC)
		MESSAGE(SEND_ERROR "stdint.h is not present and no usable alternative was found\n")
	ENDIF (MSVC)
ENDIF (NOT HAVE_STDINT_H)
